name: AntiXrayPlus
version: ${project.version}
main: dev.orf1.plugins.antixrayplus.Main
api-version: 1.13
commands:
  antixrayplus:
    aliases:
      - xray
      - antixray
      - xrayplus
      - axray
      - ores