name: AntiXrayPlus
version: ${project.version}
main: com.orf9.antixrayplus.Main
api-version: 1.13
load: STARTUP
commands:
  antixrayplus:
    aliases:
      - xray
      - antixray
      - xrayplus
      - axray
      - ores